### ISSUE TITLE
automate generation of UserCreation spreadsheet and ID setting

### ISSUE THREAD

**Issue by fcollman** [fcollman/MMSalesforceGsuite#1]
presently deployement requires the manual creation of a user creation google sheet and noting the ID of this sheet.  this could be automated, simplifying and making deployment more robust.

**Comment by fcollman** [comment]
this also applies to UserSuspension

**Comment by fcollman** [comment]
This is being addressed by #8

**Comment by aellahi** [comment]
DONE!
